sudo: required
language: php
dist: trusty

install:
  - travis_retry composer install --no-interaction

php:
  - 7.0

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.dusk .env
  - php artisan key:generate
  - php artisan serve &

script:
  - php artisan dusk
  - vendor/bin/phpunit --debug --no-coverage